### ISSUE TITLE
Thank you and some questions

### ISSUE THREAD

**Issue by SkateWarp** [xaxexa/ESPHome-TCLAC#1]
First of all, thank you for your work!
Mi air conditioner isn't exactly a TCL (an Airmax), but your custom component works (almost) correctly!
Do you plans to implement other functions, like turning off/on the display and the beeps?
I tried to implement by myself that part, but for some reason my A/C gets stuck in Auto only.
It'd be nice to have an auto-detect (and rename?) capabilities. 
Other options, like "low" or "middle" don't do anything, goes automatically to Auto.

**Comment by xaxexa** [comment]
hello, have a look here, maybe it will help you https://github.com/htmltiger/tcl-electriq-split-ac
