### ISSUE TITLE
ESP Connection

### ISSUE THREAD

**Issue by kospan** [xaxexa/ESPHome-TCLAC#2]
ESP Connection 
Which ESP model did you use and what is the pinout?
Have you used a logic level converter?

**Comment by xaxexa** [comment]
Hello, I use wemos d1 mini, without logic level converter, just for 5v power

**Comment by kospan** [comment]
it works but my TCL turns off when i change its temperature.

**Comment by xaxexa** [comment]
> it works but my TCL turns off when i change its temperature.

I listened to uart messages specifically from my air conditioner, and debugged on it, I can’t help you, maybe you have a different model or firmware version
